/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Odev3;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.util.ArrayList;
import java.util.Arrays;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }



    @Test
    public void testNullArray(){
        
        java.util.ArrayList<Integer> inputList = new java.util.ArrayList<>();
        assertNotNull(inputList);
    }
    
    @Test
    public void testNotNull(){
       
        java.util.ArrayList<Integer> array = new java.util.ArrayList<>();
        App.topla(array, 1, 1, 1);
        assertNotNull(array);
    }

    /*
    @Test public void testMiss(){
        java.util.ArrayList<Integer> array = new java.util.ArrayList<>();
        int sayi1 = 2;
        int sayi2 = 2;
        int sayi3= 1;
        assertTrue(App.topla(array,sayi1,sayi2,sayi3));
    }
    */
}
